import Head from 'next/head'
import { RecipeList } from "../widgets";

import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux'

import { UserAction } from '../store';

import styles from '../styles/Home.module.css'

export default function Home() {
  
  const {
    auth,
    user
  } = useSelector(({auth, user}) => {
    return {
      auth,
      user
    }
  });

  const dispatch = useDispatch();

  useEffect(() => {
    if(!auth.loggedIn) return;
    dispatch(
      UserAction.getHomeFeed(auth.user.user_id)
    );
    dispatch(
      UserAction.getActivityFeed(auth.user.user_id)
    );
  }, [dispatch, auth.loggedIn, auth.user.user_id]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Cookbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <RecipeList 
        recipes={user.feed.home.recipes}
      />
    
    </div>
  )
}
